name: portfolio
description: "Personal Flutter Web portfolio — Clean Architecture, Cubit, GetIt."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State management — Cubit ONLY
  flutter_bloc: ^8.1.5

  # Dependency Injection
  get_it: ^7.7.0

  # Networking (data layer only)
  http: ^1.2.1

  # Opening external links (live demo, GitHub repo, Play Store)
  url_launcher: ^6.3.2

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  bloc_test: ^9.1.7

flutter:
  uses-material-design: true
